services:
  - type: worker
    name: intraday-algo-bot
    runtime: python
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: DHAN_CLIENT_ID
        value: 1000675006
      - key: DHAN_ACCESS_TOKEN
        value: your_token_here
      - key: TELEGRAM_BOT_TOKEN
        value: your_telegram_bot_token
      - key: TELEGRAM_CHAT_ID
        value: your_chat_id
